### ISSUE TITLE
Outdated on Clojars

### ISSUE THREAD

**Issue by bsima** [boxuk/trello#5]
*For anyone else that finds this library and is confused*

It took me a while to figure this out, but this source code is **not** the same as that which is on Clojars. The latest commit on Clojars is 135172bcae196e7f2085fddee127a697680bb08d

There are a few small API changes between master and Clojars. Use [`clojure.repl/source` and `clojure.repl/doc`](http://clojure.github.io/clojure/clojure.repl-api.html) to find the correct functions. [This trick to show all functions in a namespace](http://stackoverflow.com/questions/2747294/how-to-list-the-functions-of-a-namespace) is also helpful.

**Comment by bsima** [comment]
On that note, @owainlewis @rodnaph:

I'm using this over at nebulabio/www@stripe-backend, and I'm patching the namespace in order to add missing functionality, such as `get-member`, `get-label`, etc. Unfortunately, since Clojars is outdated, the functions I'm writing won't be entirely compatible with master (I'm using `request` instead of `->>request`, for example). I also think the API could use some improvement, for example you have `board` and `get-card`. More consistent naming would be ideal.

I really need a Trello library, since Trello is basically the backend for persisting our tasks (in combination with a db), so if you guys want I'll pick this up and maintain it. The core code is pretty good, just needs some [love :)](https://www.youtube.com/watch?v=Xe1TZaElTAs)

FWIW, [trellolib](https://github.com/jbatch/trellolib/) is another option, but it doesn't actually implement any of the API, it just establishes and OAuth connection.

**Comment by rodnaph** [comment]
Hey @bsima - @owainlewis actually wrote, well pretty much all of it I think.  But unfortunately both of us have left Box UK, so don't have any permissions on the repo.

If you want to fork and start maintaining it though I'm sure @jenkoian or @Bendihossan will be able to help out with updating the README to link over...?

**Comment by bsima** [comment]
[Forked!](https://github.com/bsima/trello)

**Comment by jenkoian** [comment]
Hey @bsima,

As @rodnaph alluded too, this repository isn't really maintained. If you're happy to pick it up, I'll put a note on the README directing people to your fork?

**Comment by bsima** [comment]
That'd be great, thank @jenkoian! I'll be working on it a lot over the course of this week.

**Comment by jenkoian** [comment]
Thanks @bsima 
https://github.com/boxuk/trello/commit/9d9ea29568374d8e026081a0849bfab96ed2001e
